name: github_repos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  retrofit: 4.4.0
  logger: 2.4.0
  injectable: 2.5.0
  get_it: 8.0.0
  flutter_bloc: 8.1.6
  cached_network_image: 3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.8.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  injectable_generator: 2.6.2
  mocktail: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - mocks/